package dev.dynamicvector.screens

import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.lazy.grid.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.outlined.ArrowBack
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import dev.dynamicvector.components.*
import dev.dynamicvector.data.MockData
import dev.dynamicvector.model.*
import dev.dynamicvector.navigation.QueryCreationMode
import dev.dynamicvector.theme.DVColors
import dev.dynamicvector.theme.DVTypography

@Composable
fun NewQueryScreen(onBack: () -> Unit) {
    var mode by remember { mutableStateOf(QueryCreationMode.DESCRIBE) }
    var queryName by remember { mutableStateOf("") }

    Column(Modifier.fillMaxSize()) {
        Spacer(Modifier.height(44.dp))
        Row(Modifier.padding(horizontal = 16.dp, vertical = 12.dp), verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(12.dp)) {
            Box(Modifier.size(32.dp).background(DVColors.Accent.copy(0.08f), RoundedCornerShape(10.dp)).clickable(onClick = onBack), contentAlignment = Alignment.Center) {
                Icon(Icons.AutoMirrored.Outlined.ArrowBack, "Back", tint = DVColors.Accent, modifier = Modifier.size(16.dp))
            }
            Text("New query", style = DVTypography.H1.copy(fontSize = 18.sp))
        }

        // Mode switcher
        Row(Modifier.padding(horizontal = 16.dp, vertical = 4.dp).fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
            data class M(val m: QueryCreationMode, val icon: String, val label: String, val sub: String, val bg: Color)
            listOf(
                M(QueryCreationMode.DESCRIBE, "✦", "Describe", "AI builds it from your words", DVColors.AccentDim),
                M(QueryCreationMode.BUILD, "⚙", "Build", "Manual step-by-step config", DVColors.QdrantBg),
                M(QueryCreationMode.TEMPLATES, "☷", "Templates", "Start from community presets", DVColors.StatusStale.copy(0.15f)),
            ).forEach { m ->
                val active = m.m == mode
                Column(Modifier.weight(1f).background(if (active) DVColors.Accent.copy(0.08f) else DVColors.SurfaceVariant, RoundedCornerShape(14.dp))
                    .border(1.dp, if (active) DVColors.AccentBorder else DVColors.CardBorder, RoundedCornerShape(14.dp))
                    .clickable { mode = m.m }.padding(horizontal = 8.dp, vertical = 14.dp), horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Box(Modifier.size(40.dp).background(m.bg, RoundedCornerShape(12.dp)), contentAlignment = Alignment.Center) { Text(m.icon, fontSize = 18.sp) }
                    Text(m.label, fontSize = 12.sp, fontWeight = FontWeight.SemiBold, color = if (active) DVColors.Accent else DVColors.TextTertiary)
                    Text(m.sub, fontSize = 10.sp, color = DVColors.TextHint, lineHeight = 13.sp, textAlign = TextAlign.Center, maxLines = 2)
                }
            }
        }

        when (mode) {
            QueryCreationMode.DESCRIBE -> DescribeContent(queryName) { queryName = it }
            QueryCreationMode.BUILD -> BuildContent(queryName) { queryName = it }
            QueryCreationMode.TEMPLATES -> TemplatesContent { mode = QueryCreationMode.BUILD }
        }
    }
}

@Composable private fun DescribeContent(queryName: String, onNameChange: (String) -> Unit) {
    var text by remember { mutableStateOf("") }
    var generated by remember { mutableStateOf(false) }
    LazyColumn(contentPadding = PaddingValues(bottom = 88.dp)) {
        item {
            Column(Modifier.padding(16.dp).fillMaxWidth().background(DVColors.Accent.copy(0.04f), RoundedCornerShape(16.dp))
                .border(1.dp, DVColors.Accent.copy(0.12f), RoundedCornerShape(16.dp)).padding(16.dp)) {
                Text("DESCRIBE WHAT YOU WANT", style = DVTypography.SectionLabel.copy(color = DVColors.Accent.copy(0.5f)), modifier = Modifier.padding(bottom = 10.dp))
                OutlinedTextField(value = text, onValueChange = { text = it },
                    placeholder = { Text("e.g. Find eco-friendly outdoor gear under CHF 200 near Bern...", color = DVColors.Accent.copy(0.3f), fontSize = 14.sp) },
                    minLines = 3, colors = OutlinedTextFieldDefaults.colors(focusedContainerColor = DVColors.Accent.copy(0.04f), unfocusedContainerColor = DVColors.Accent.copy(0.04f),
                        focusedBorderColor = DVColors.Accent.copy(0.08f), unfocusedBorderColor = DVColors.Accent.copy(0.08f), cursorColor = DVColors.Accent, focusedTextColor = DVColors.TextPrimary, unfocusedTextColor = DVColors.TextPrimary),
                    shape = RoundedCornerShape(12.dp), modifier = Modifier.fillMaxWidth())
                Spacer(Modifier.height(12.dp))
                Button(onClick = { generated = true }, enabled = text.isNotBlank(), colors = ButtonDefaults.buttonColors(containerColor = DVColors.Accent, contentColor = Color.White),
                    shape = RoundedCornerShape(12.dp), modifier = Modifier.fillMaxWidth().height(44.dp)) { Text("✦  Generate query", fontWeight = FontWeight.Bold, fontSize = 13.sp) }
                if (generated) { Spacer(Modifier.height(12.dp)); GenPreview() }
                Spacer(Modifier.height(10.dp))
                Text("You can edit any step after generating. Tap \"Build\" to switch to the manual editor with these steps pre-loaded.", fontSize = 11.sp, color = DVColors.Accent.copy(0.35f), lineHeight = 16.sp)
            }
        }
        item { QField("Query name", queryName, onNameChange) }
        item { SchedToggle() }
        item { SaveBtn() }
    }
}

@Composable private fun GenPreview() {
    data class S(val color: Color, val text: String)
    val steps = listOf(S(DVColors.Qdrant, "Search products for \"outdoor gear\""), S(DVColors.Apify, "Scrape prices with price_tracker"), S(DVColors.LiveMap, "Filter within 30 km of Bern"), S(DVColors.StatusStale, "Set budget max CHF 200"), S(DVColors.Accent, "Suggest top 10 by sustainability"))
    Column(Modifier.fillMaxWidth().background(DVColors.Accent.copy(0.05f), RoundedCornerShape(12.dp)).border(1.dp, DVColors.Accent.copy(0.12f), RoundedCornerShape(12.dp)).padding(12.dp)) {
        Text("GENERATED PIPELINE", fontSize = 10.sp, fontWeight = FontWeight.SemiBold, color = DVColors.Accent.copy(0.4f), letterSpacing = 0.8.sp, modifier = Modifier.padding(bottom = 8.dp))
        steps.forEachIndexed { i, s ->
            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.padding(vertical = 4.dp)) {
                Box(Modifier.size(6.dp).background(s.color, CircleShape))
                Text(s.text, fontSize = 12.sp, color = DVColors.TextTertiary, lineHeight = 16.sp)
            }
            if (i < steps.lastIndex) Text("↓", fontSize = 10.sp, color = DVColors.TextHint, modifier = Modifier.padding(start = 14.dp))
        }
    }
}

@Composable private fun BuildContent(queryName: String, onNameChange: (String) -> Unit) {
    val steps = remember { MockData.pipelineSteps }
    LazyColumn(contentPadding = PaddingValues(bottom = 88.dp)) {
        item { QField("Query name", queryName, onNameChange) }
        item { SectionHeader("Pipeline steps") }
        itemsIndexed(steps) { i, step ->
            PipelineBlock(step)
            if (i < steps.lastIndex) Text("↓", color = DVColors.TextHint, fontSize = 18.sp, modifier = Modifier.fillMaxWidth().padding(vertical = 2.dp).wrapContentWidth(Alignment.CenterHorizontally))
        }
        item { Box(Modifier.padding(horizontal = 16.dp, vertical = 8.dp).fillMaxWidth().background(DVColors.SurfaceVariant, RoundedCornerShape(14.dp)).border(1.dp, DVColors.TextHint, RoundedCornerShape(14.dp)).padding(12.dp), contentAlignment = Alignment.Center) { Text("+ Add step", color = DVColors.TextTertiary, fontSize = 13.sp) } }
        item {
            Column(Modifier.padding(horizontal = 16.dp, vertical = 8.dp)) {
                Text("TEXT REFINEMENT (OPTIONAL)", style = DVTypography.SectionLabel, modifier = Modifier.padding(bottom = 8.dp))
                Box(Modifier.fillMaxWidth().background(DVColors.SurfaceVariant, RoundedCornerShape(12.dp)).border(1.dp, DVColors.CardBorder, RoundedCornerShape(12.dp)).padding(12.dp)) {
                    Text("I prefer brands with verified eco-certifications. Swiss-made or European-made is a plus.", fontSize = 13.sp, color = DVColors.TextSecondary, lineHeight = 18.sp)
                }
            }
        }
        item { SchedToggle() }
        item { SaveBtn() }
    }
}

@Composable private fun TemplatesContent(onUse: () -> Unit) {
    var filter by remember { mutableStateOf("All") }
    Column {
        DVSearchBar("", {}, "Search templates...", modifier = Modifier.padding(vertical = 8.dp))
        LazyRow(contentPadding = PaddingValues(horizontal = 16.dp, vertical = 4.dp), horizontalArrangement = Arrangement.spacedBy(6.dp)) {
            items(listOf("All", "Retail", "Finance", "Healthcare", "B2B", "Personal")) { cat ->
                val a = cat == filter
                Box(Modifier.background(if (a) DVColors.AccentDim else DVColors.SurfaceVariant, RoundedCornerShape(20.dp)).border(1.dp, if (a) DVColors.AccentBorder else DVColors.CardBorder, RoundedCornerShape(20.dp)).clickable { filter = cat }.padding(horizontal = 14.dp, vertical = 6.dp)) {
                    Text(cat, fontSize = 12.sp, fontWeight = FontWeight.SemiBold, color = if (a) DVColors.Accent else DVColors.TextTertiary)
                }
            }
        }
        SectionHeader("Popular templates")
        LazyVerticalGrid(GridCells.Fixed(2), contentPadding = PaddingValues(horizontal = 16.dp, vertical = 4.dp), horizontalArrangement = Arrangement.spacedBy(10.dp), verticalArrangement = Arrangement.spacedBy(10.dp), modifier = Modifier.weight(1f)) {
            items(MockData.templates) { tpl ->
                Column(Modifier.fillMaxWidth().background(DVColors.SurfaceVariant, RoundedCornerShape(14.dp)).border(1.dp, DVColors.CardBorder, RoundedCornerShape(14.dp)).clickable(onClick = onUse).padding(14.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Box(Modifier.size(32.dp).background(tpl.iconBg, RoundedCornerShape(8.dp)), contentAlignment = Alignment.Center) { Text(tpl.icon, fontSize = 16.sp) }
                    Text(tpl.name, fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = DVColors.TextPrimary)
                    Text(tpl.description, fontSize = 11.sp, color = DVColors.TextTertiary, lineHeight = 15.sp, maxLines = 3)
                    Row(horizontalArrangement = Arrangement.spacedBy(4.dp)) { tpl.sources.forEach { SourceBadge(it) } }
                    Text("Use template →", fontSize = 11.sp, fontWeight = FontWeight.SemiBold, color = DVColors.Accent)
                }
            }
        }
    }
}

@Composable private fun QField(label: String, value: String, onChange: (String) -> Unit) {
    Column(Modifier.padding(horizontal = 16.dp, vertical = 8.dp)) {
        Text(label.uppercase(), style = DVTypography.SectionLabel, modifier = Modifier.padding(bottom = 8.dp))
        OutlinedTextField(value = value, onValueChange = onChange, placeholder = { Text("Name your query...", color = DVColors.TextHint, fontSize = 14.sp) }, singleLine = true,
            colors = OutlinedTextFieldDefaults.colors(focusedContainerColor = DVColors.SurfaceVariant, unfocusedContainerColor = DVColors.SurfaceVariant, focusedBorderColor = DVColors.CardBorder, unfocusedBorderColor = DVColors.CardBorder, cursorColor = DVColors.Accent, focusedTextColor = DVColors.TextPrimary, unfocusedTextColor = DVColors.TextPrimary),
            shape = RoundedCornerShape(12.dp), modifier = Modifier.fillMaxWidth())
    }
}

@Composable private fun SchedToggle() {
    var on by remember { mutableStateOf(false) }
    Row(Modifier.padding(horizontal = 16.dp, vertical = 8.dp).fillMaxWidth().background(DVColors.SurfaceVariant, RoundedCornerShape(12.dp)).border(1.dp, DVColors.CardBorder, RoundedCornerShape(12.dp)).padding(horizontal = 16.dp, vertical = 14.dp), Arrangement.SpaceBetween, Alignment.CenterVertically) {
        Column { Text("Run automatically", fontSize = 14.sp, color = DVColors.TextPrimary); Text(if (on) "Every 6 hours" else "Not scheduled", style = DVTypography.Caption) }
        Switch(checked = on, onCheckedChange = { on = it }, colors = SwitchDefaults.colors(checkedThumbColor = DVColors.Accent, checkedTrackColor = DVColors.Accent.copy(0.3f), uncheckedThumbColor = DVColors.TextTertiary, uncheckedTrackColor = DVColors.SurfaceVariant))
    }
}

@Composable private fun SaveBtn() {
    Button(onClick = {}, colors = ButtonDefaults.buttonColors(containerColor = DVColors.Accent, contentColor = Color.White), shape = RoundedCornerShape(14.dp),
        modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 8.dp).height(50.dp)) { Text("Save & run query", fontWeight = FontWeight.Bold, fontSize = 14.sp) }
}
